Add conditional steps for failure handling in workflow

diff --git a/.github/workflows/conditional.yaml b/.github/workflows/conditional.yaml
--- a/.github/workflows/conditional.yaml
+++ b/.github/workflows/conditional.yaml
@@ -7,3 +7,10 @@ jobs:
       - name: check if main
         if: github.ref == 'refs/heads/main'
         run: echo "this runs only if it is main branch"
+
+      - name: failed step
+        run: exit 1
+
+      - name: run if previous step failed
+        if: ${{ failure() && steps.demo.conclusion == 'failure' }}
+        run: echo "this runs if previous step fails" 
